CREATE SCHEMA IF NOT EXISTS CarDatabase DEFAULT CHARACTER SET utf8;
USE CarDatabase;

CREATE TABLE IF NOT EXISTS CarDatabase.cars(
	Id INTEGER NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (Id),
    Color VARCHAR(50) NOT NULL,
    Type VARCHAR(50) NOT NULL,
    Year DATETIME NOT NULL,
    Price INT NOT NULL
    );
    
CREATE TABLE IF NOT EXISTS CarDatabase.shops(
	Id INTEGER NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (Id),
    Location VARCHAR(20) NOT NULL,
    Owner Varchar(20) NOT NULL
    );
    
CREATE TABLE IF NOT EXISTS CarDatabase.visiting(
	Id INTEGER NOT NULL AUTO_INCREMENT,
    PRIMARY KEY(Id),
    Time DATETIME NOT NULL
    );
	
CREATE TABLE IF NOT EXISTS CarDatabase.register(
	Id INTEGER NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (Id),
    CarID INTEGER NOT NULL,
    FOREIGN KEY (CarID) 
		REFERENCES cars (Id),
    ShopID INTEGER NOT NULL,
    FOREIGN KEY (ShopID) 
		REFERENCES shops (Id),
    TimeID INTEGER NOT NULL,
    FOREIGN KEY (TimeID) 
		REFERENCES visiting (Id)
	);